name: Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      P6_DFZ_SRC_P6M7G8_DIR: ".."
      TERM: "xterm-256color"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deps
        run:  /bin/sh -x ./bin/deps.sh
        shell: sh
      - name: Build
        run:  /bin/sh ../p6ctl/bin/p6ctl -d build
        shell: sh
    container:
      image: docker
  build-bare:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      P6_DFZ_SRC_P6M7G8_DIR: ".."
      TERM: "xterm-256color"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run:  bin/p6ctl build
