name: Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      P6_DFZ_SRC_P6M7G8_DIR: ".."
      TERM: "xterm-256color"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: /bin/sh scripts/test.sh
    container:
      image: scottw/alpine-perl
